# Generated by Django 6.0.5 on 2026-05-24 20:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('etudiant', 'Etudiant'), ('enseignant', 'Enseignant'), ('superviseur', 'Superviseur'), ('responsable', 'Responsable de Master'), ('admin', 'Administrateur'), ('jury', 'Membre de jury')], max_length=30, unique=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.role'),
        ),
    ]
