# Generated by Django 6.0.5 on 2026-05-30 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('archivee', 'Archivée')], default='en_cours', max_length=20)),
            ],
            options={
                'db_table': 'academic_years',
                'ordering': ['-date_debut'],
            },
        ),
    ]
