# Generated by Django 6.0.5 on 2026-05-30 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('resume', models.TextField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('competences_requises', models.TextField(blank=True, null=True)),
                ('mots_cles', models.CharField(blank=True, max_length=255, null=True)),
                ('capacite', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('complet', 'Complet'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('encadrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_encadres', to='teachers.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='semesters.semester')),
                ('superviseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_supervises', to='teachers.teacher')),
            ],
        ),
    ]
