# Generated by Django 6.0.5 on 2026-06-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='encadrant',
            new_name='enseignant',
        ),
    ]
