# Generated by Django 6.0.5 on 2026-06-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='date_debut_soutenances',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='date_fin_soutenances',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='date_limite_candidatures',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='date_limite_documents',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='date_limite_sujets',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.academicyear'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé')], default='ferme', max_length=20),
        ),
        migrations.AlterModelTable(
            name='semester',
            table='semesters',
        ),
    ]
